FROM node:lts-alpine as builder

WORKDIR /server

COPY tsconfig.json tsconfig.json
COPY package.json package.json

RUN npm install
RUN npm install -g typescript

COPY src src

RUN tsc

FROM node:lts-alpine

RUN apk --no-cache add curl

WORKDIR /server

COPY --from=builder /server/dist /server/dist

COPY package.json package.json

RUN npm install --production

CMD npm run startprod